language: elixir
cache:
  directories:
    - $HOME/.mix
elixir:
  - 1.13.4
otp_release:
  - 24.3.1
before_script:
  - export MIX_HOME=$HOME/.mix
  - export MIX_ENV=test
  - chmod +x bin/setup
  - chmod +x bin/test
script:
  - bin/setup
